/*
* Author:	Angelo Frasca Caccia ( lem0nSec_ )
* Title:	KBlast.exe ( client )
* Website:	https://github.com/lem0nSec/KBlast
*/


#pragma once

#define KBLAST_DEVICE											0x8000
#define KBLAST_IOCTL_TEST										CTL_CODE(KBLAST_DEVICE, 0x801, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_BUG_CHECK									CTL_CODE(KBLAST_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_MEMORY_WRITE								CTL_CODE(KBLAST_DEVICE, 0x803, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_MEMORY_READ								CTL_CODE(KBLAST_DEVICE, 0x804, METHOD_NEITHER, FILE_ANY_ACCESS)

#define KBLAST_IOCTL_PROTECT_WINTCB								CTL_CODE(KBLAST_DEVICE, 0x901, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_PROTECT_LSA								CTL_CODE(KBLAST_DEVICE, 0x902, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_PROTECT_ANTIMALWARE						CTL_CODE(KBLAST_DEVICE, 0x903, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_PROTECT_NONE								CTL_CODE(KBLAST_DEVICE, 0x904, METHOD_NEITHER, FILE_ANY_ACCESS)

#define KBLAST_IOCTL_TOKEN_PRIVILEGES_ENABLEALL					CTL_CODE(KBLAST_DEVICE, 0xA00, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_TOKEN_PRIVILEGES_DISABLEALL				CTL_CODE(KBLAST_DEVICE, 0xA01, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_TOKEN_STEAL								CTL_CODE(KBLAST_DEVICE, 0xA02, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_TOKEN_RESTORE								CTL_CODE(KBLAST_DEVICE, 0xA03, METHOD_NEITHER, FILE_ANY_ACCESS)

#define KBLAST_IOCTL_CALLBACK_PROCESS_LIST						CTL_CODE(KBLAST_DEVICE, 0xB01, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_CALLBACK_THREAD_LIST						CTL_CODE(KBLAST_DEVICE, 0xB02, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_CALLBACK_IMAGE_LIST						CTL_CODE(KBLAST_DEVICE, 0xB03, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLAST_IOCTL_CALLBACK_REGISTRY_LIST						CTL_CODE(KBLAST_DEVICE, 0xB04, METHOD_NEITHER, FILE_ANY_ACCESS)