/*
* Author:	Angelo Frasca Caccia ( lem0nSec_ )
* Title:	KBlaster.sys ( driver )
* Website:	https://github.com/lem0nSec/KBlast
*/


#pragma once

#define KBLASTER_DEVICE											0x8000
#define KBLASTER_IOCTL_MISC_BUG_CHECK							CTL_CODE(KBLASTER_DEVICE, 0x802, METHOD_NEITHER, FILE_ANY_ACCESS)
#define KBLASTER_IOCTL_MISC_MEMORY								CTL_CODE(KBLASTER_DEVICE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define KBLASTER_IOCTL_PROTECTION								CTL_CODE(KBLASTER_DEVICE, 0x901, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define KBLASTER_IOCTL_TOKEN_PRIVILEGES							CTL_CODE(KBLASTER_DEVICE, 0xA00, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define KBLASTER_IOCTL_TOKEN_CONTEXT							CTL_CODE(KBLASTER_DEVICE, 0xA01, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define KBLASTER_IOCTL_CALLBACK_ENUM							CTL_CODE(KBLASTER_DEVICE, 0xB01, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define KBLASTER_IOCTL_CALLBACK_REMOVE							CTL_CODE(KBLASTER_DEVICE, 0xB02, METHOD_IN_DIRECT, FILE_ANY_ACCESS)

#define KBLASTER_IOCTL_PROCESS_ENUMERATE						CTL_CODE(KBLASTER_DEVICE, 0xC01, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define KBLASTER_IOCTL_PROCESS_TERMINATE						CTL_CODE(KBLASTER_DEVICE, 0xC02, METHOD_BUFFERED, FILE_ANY_ACCESS)
